apiVersion: cert-manager.io/v1 
kind: Certificate
metadata:
  name: elainemay-net-tls
spec:
  secretName: elainemay-net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: elainemay.net
  dnsNames:
    - elainemay.net
    - www.elainemay.net